### ISSUE TITLE
is there any way to make it non endless.( i created issue in wrong repo .please delete this or modify ,sorry).

### ISSUE THREAD

**Issue by aka-awasthi** [applm/CarouselWidget#8]
![screenshot_2015-11-29-14-12-17 1](https://cloud.githubusercontent.com/assets/7922097/11456147/ef59d9d4-96a3-11e5-955b-7f56469e0a0b.png)

**Comment by applm** [comment]
You mean endless? You can use modulo in adapter on index.

**Comment by aka-awasthi** [comment]
i  did shouldRepeat false.
after this i get like above screenshot with no scrolling and having a crash.

**Comment by applm** [comment]
There is no shouldRepeat in this version.

**Comment by aka-awasthi** [comment]
i want carousel running with shouldrepeat false. but i dont know how to achieve that.

**Comment by applm** [comment]
Are you sure you are commenting on the right repository?

**Comment by aka-awasthi** [comment]
sorry i am not .i created issue in wrong repo.it was for coverflowdemo and i created in carousel widget.
can u delete that issue??
