### ISSUE TITLE
Refreshing Adapter

### ISSUE THREAD

**Issue by GauravCreed** [applm/CarouselWidget#9]
hi Martin

you have done a great job for the new beginner for the android , i have a issue to refresh the adapter how can i possible??

i have create a own layout for the CarouselWidget coverflow and integrate it will work perfectly but when i remove the item from that view it will not refresh please help me.

i have also try notifyDataSetChanged() of the adapter but unfortunately it will not work.

Thanks.

**Comment by GauravCreed** [comment]
Hi Martin

i have face another problem that is, when i delete some item from CarouselWidget and then after
 CarouselWidget item display starting from beginning, 

so haw can i display CarouselWidget for the specific position in CarouselWidget item list ,is there any solution for that 

thanks.

**Comment by beersheba** [comment]
> so haw can i display CarouselWidget for the specific position in CarouselWidget item list ,is there any solution for that

```
    CoverFlowCarousel galleryFlow = (CoverFlowCarousel) findViewById(R.id.coverflow);
    galleryFlow.setSelection(1);
```

**Comment by GauravCreed** [comment]
Hey @applm 

it will work fine now,Thanks for your response and code both, now you can close this iisue.

Thanks.
